version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - ci

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      testing:
        patterns:
          - "junit*"
          - "org.robolectric*"
          - "androidx.test*"
