build:
  maxIssues: 0
  excludeCorrectionPatterns:
    - '.*test.*'
    - '.*Test.*'

config:
  validation: true
  warningThreshold: 0
  excludePatterns:
    - '.*/resources/**'
    - '.*/build/**'

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  EndOfLineComment:
    active: false
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  CognitiveComplexMethod:
    active: true
    threshold: 15
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LabeledExpression:
    active: false
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter:
      - 'Inject'
      - 'AssistedInject'
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 4
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: true
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBody:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBody:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

errorprone:
  active: true
  CastToNullableType:
    active: false
  Deprecation:
    active: false
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsFalseOrTrue:
    active: true
  EqualsWithHashCodeExactlyReturnsInt:
    active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
  HasPlatformType:
    active: true
  ImplicitDefaultLocale:
    active: true
  InvalidRange:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: false
  MissingPackageDeclaration:
    active: false
  NullCheckZeroComparison:
    active: true
  NullableToStringCall:
    active: true
  NullInsteadOfEmptyCollection:
    active: true
  NullInsteadOfEmptyMap:
    active: true
  NullInsteadOfEmptySet:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  ReplaceNotNullAssertionWithElvisReturn:
    active: false
  ReturnFromFinally:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: false
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
  ObjectExtendsThrowable:
    active: false
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: false
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true

formatting:
  active: true
  autoCorrect: false
  ChainWrapping:
    active: true
    autoCorrect: false
  CommentSpacing:
    active: true
    autoCorrect: true
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: true
  ImportOrdering:
    active: true
    autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
    ignoreBackTickedIdentifier: false
  ModifierOrdering:
    active: true
    autoCorrect: true
  MultiLineIfElseBlock:
    active: true
    autoCorrect: false
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingComma:
    active: false
    autoCorrect: false
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: false
  PackageName:
    active: true
  ParameterListWrapping:
    active: true
    autoCorrect: false
    indentSize: 4
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundDoubleColon:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  SpacingBeforeComma:
    active: true
    autoCorrect: true
  TrailingCommaOnArgumentList:
    active: false
    autoCorrect: false
  TrailingCommaOnCall:
    active: false
    autoCorrect: false
  TrailingCommaOnDeclarationList:
    active: false
    autoCorrect: false
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
    autoCorrect: true

naming:
  active: true
  BooleanPropertyNaming:
    active: false
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  EnumNaming:
    active: true
    enumPattern: '[A-Z][a-zA-Z0-9]*'
  ForbiddenClassName:
    active: false
  FunctionMaxLength:
    active: false
  FunctionMinLength:
    active: false
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$_][a-zA-Z$_0-9]*)|(`.*`)$'
    excludeClassPattern: '$^'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreOverriddenFunctions: true
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    active: true
    mustBeFirst: true
  MemberNameEqualsClassName:
    active: true
    ignoreOverriddenFunction: true
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][a-zA-Z0-9]*'
    privatePropertyPattern: '(_)?[a-z][a-zA-Z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][a-zA-Z0-9]*'
    privatePropertyPattern: '_?[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
    privateVariablePattern: '(_)?[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreOverriddenFunction: true

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: false
  ForEachOnRange:
    active: true
    excludeEnums: true
    excludeAnnotationClasses: true
    excludeDataClasses: true
  SpreadOperator:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  Deprecation:
    active: false
  DontDowncastCollectionCast:
    active: false
  DoubleMutabilityForCollection:
    active: false
  DuplicateCheckInElseIfChain:
    active: false
  ElseCaseInsteadOfExhaustiveWhen:
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  ImplicitDefaultLocale:
    active: false
  ImplicitUnitReturnType:
    active: false
  InvalidRange:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: false
  MissingWhileDefaultCase:
    active: false
  NullCheckZeroComparison:
    active: true
  NullableToStringCall:
    active: false
  NullInsteadOfEmptyCollection:
    active: true
  NullInsteadOfEmptyMap:
    active: true
  NullInsteadOfEmptySet:
    active: true
  PropertyUsedBeforeDeclaration:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  ReplaceNotNullAssertionWithElvisReturn:
    active: false
  ReplaceWithEnumMap:
    active: false
  ReplaceWithIsEmpty:
    active: true
  ReturnFromFinally:
    active: false
  SelfComparison:
    active: true
  SuspiciousCollectionReassignment:
    active: true
  SuspiciousEquality:
    active: false
  SuspiciousListReassignment:
    active: true
  SuspiciousMutableSharedVariable:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: false
  UselessPostfixExpression:
    active: false

style:
  active: true
  AlsoCouldBeApply:
    active: false
  BracesOnIfStatements:
    active: false
  BracesOnWhenStatements:
    active: false
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: false
  ClassOrderingProperties:
    active: false
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: true
  DestructuringAssignmentWithTooManyEntries:
    active: false
  EqualsNullCall:
    active: true
  EqualsOnNullableType:
    active: true
  EqualsToReferenceComparison:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
  FlatMapSequence:
    active: true
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: false
  ForbiddenMethod:
    active: false
  ForbiddenPublicDataClass:
    active: false
  ForbiddenVoid:
    active: false
  FunctionOnlyReturningConstant:
    active: true
  LibraryCodeMustSpecifyReturnType:
    active: true
  LibraryEntitiesShouldNotBePublic:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  MandatoryBracesLoops:
    active: false
  MaxLineLength:
    active: false
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
  MultilineLambdaItParameterNaming:
    active: false
  MultilineRawStringIndentation:
    active: false
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: true
  ObjectLiteralToLambda:
    active: false
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedVariableInInterface:
    active: true
  RedundantExplicitType:
    active: false
  RedundantHigherOrderMapUsage:
    active: true
  RedundantInnerClassModifier:
    active: true
  RedundantSuspendModifier:
    active: true
  RedundantVisibilityModifier:
    active: true
  RedundantVisibilityModifierForExtensionDeclaration:
    active: false
  RepeatedBySequence:
    active: true
  RepeatedUnaryOperator:
    active: true
  ReplaceArrayOfWithLiteral:
    active: false
  ReplaceCallWithBinaryOperator:
    active: false
  ReplaceGetOrSet:
    active: false
  ReplaceIfWithWhen:
    active: false
  ReplaceMapWithFlatMap:
    active: true
  ReplaceNegatedIsEmptyWithIsNotEmpty:
    active: true
  ReplaceNotNullAssertionWithElvisReturn:
    active: true
  ReplaceOnSequenceWithMap:
    active: false
  ReplaceRangeToUntil:
    active: true
  ReplaceRangeStartEndInclusiveWithUntil:
    active: true
  ReplaceToWithInfixForm:
    active: false
  ReplaceUntilWithRangeUntil:
    active: true
  ReplaceWhenWithIf:
    active: false
  ReturnCount:
    active: false
  SafeCast:
    active: true
  SerialVersionUidInSerializableClass:
    active: false
  SpreadOperator:
    active: true
  StringShouldBeRawString:
    active: false
  SuspiciousComment:
    active: false
  ThrowsCount:
    active: false
  TrailingWhitespace:
    active: false
  TrimMultilineString:
    active: false
  TryKeywordUsage:
    active: false
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryAnnotationUsageOnAnnotationClass:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryNotNullCheck:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessaryParentheses:
    active: true
  UnnecessaryPrimaryConstructor:
    active: true
  UnnecessarySafeCall:
    active: true
  UnnecessaryStringEscape:
    active: true
  UnnecessaryStringInterpolation:
    active: true
  UnnecessaryToDo:
    active: false
  UnnecessaryWhenExpression:
    active: true
  UnnecessaryWildcardImport:
    active: true
  UnnamedParameter:
    active: false
  UnusedImports:
    active: true
  UnusedParameter:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  UnusedSecondaryConstructor:
    active: true
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: false
  UseDataClass:
    active: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: false
  UseIfInsteadOfWhen:
    active: false
  UseIsEven:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: false
  UseSameLambdaParamName:
    active: false
  UselessCallOnNotNull:
    active: true
  UselessCompareTo:
    active: true
  UselessLet:
    active: true
  UseVarKeyword:
    active: false
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
